language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov
  - luarocks install tapered

script:
  - lua -lluacov awesome-tests.lua

after_success:
  - bash -c "$(git log -1 --pretty=%B | tail -1)"
